### ISSUE TITLE
Maximize=True is useless

### ISSUE THREAD

**Issue by timruhkopf** [automl/hypersweeper#19]
* HyperSweeper version: .git@8d7fbea4c535e6b619e6e13ba457d51540f506c0#egg=HyperSweeper
* Python version: 3.10
* Operating System: Linux

#### Description
hydra.sweeper.sweeper_kwargs.maximize=True --> will result in double negation and thus is rendered useless.

#### Additional Info

- Did you try upgrading to the most current version? yes/no
- Are you using a supported operating system (version)? yes/no
- How did you install this package (e.g. GitHub, pip, etc.)?

**Comment by TheEimer** [comment]
Fixed by removing one of the double negatives
